name: Tracking Merge Queue
on:
  pull_request:
    types: ["enqueued", "dequeued"]

jobs:
  emit-enqueue:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'enqueued' }}
    steps:
      - run: echo "enqueued"

  emit-dequeue:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'dequeued' && github.event.reason != 'MERGE'}}
    steps:
      - run: |
          aws help