name: Tracking Merge Queue
on:
  pull_request:
    types: ["enqueued", "dequeued"]

jobs:
  emit-enqueue:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.action == 'enqueued' }}
    steps:
      - run: echo "enqueued"

  emit-dequeue:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.action == 'dequeued' }}
    steps:
      - run: echo "dequeued"